# Generated by Django 4.0 on 2024-04-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('apps_accounts', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('fone', models.CharField(blank=True, max_length=16, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=4, null=True)),
                ('complemento', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='apps_accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('genericprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.genericprofile')),
            ],
            bases=('profiles.genericprofile',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('genericprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.genericprofile')),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='companies.company')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sectors.sector')),
            ],
            bases=('profiles.genericprofile',),
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('genericprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.genericprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            bases=('profiles.genericprofile',),
        ),
    ]
