# Generated by Django 4.0 on 2024-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('equipmento_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipmento_name', models.CharField(max_length=10)),
                ('patrimonio', models.IntegerField(blank=True, null=True)),
                ('numero_serie', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('controle', models.CharField(blank=True, choices=[('AF', 'Aferição'), ('CA', 'Calibração'), ('CT', 'Controle'), ('EN', 'Ensaio'), ('IN', 'Inspeção')], max_length=2)),
                ('faixa_equip', models.IntegerField(blank=True, null=True)),
                ('utilizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=100, null=True)),
                ('processo_calibraço', models.TextField(blank=True, max_length=30, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('FO', 'Fora de Operação'), ('NA', 'N/A'), ('OK', 'OK'), ('PR', 'Programar'), ('VE', 'Vencido')], max_length=2)),
                ('frequneciao', models.IntegerField(blank=True, null=True)),
                ('proxima_calibracao', models.DateField()),
            ],
        ),
    ]
